# Generated by Django 3.2.8 on 2021-10-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emailId', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=10)),
                ('textholder', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
